In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/tabular-playground-series-dec-2021/sample_submission.csv
/kaggle/input/tabular-playground-series-dec-2021/train.csv
/kaggle/input/tabular-playground-series-dec-2021/test.csv

In [2]:
train = pd.read_csv("../input/tabular-playground-series-dec-2021/train.csv")
test = pd.read_csv("../input/tabular-playground-series-dec-2021/test.csv")

In [3]:
train['Cover_Type'].value_counts()

2    2262087
1    1468136
3     195712
7      62261
6      11426
4        377
5          1
Name: Cover_Type, dtype: int64

In [4]:
train=train[train['Cover_Type']!=5]

In [5]:
train.head()

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,0,3189,40,8,30,13,3270,206,234,193,...,0,0,0,0,0,0,0,0,0,1
1,1,3026,182,5,280,29,3270,233,240,106,...,0,0,0,0,0,0,0,0,0,2
2,2,3106,13,7,351,37,2914,208,234,137,...,0,0,0,0,0,0,0,0,0,1
3,3,3022,276,13,192,16,3034,207,238,156,...,0,0,0,0,0,0,0,0,0,2
4,4,2906,186,13,266,22,2916,231,231,154,...,0,0,0,0,0,0,0,0,0,2

In [6]:
# Get train data without the target and ids
X = train.iloc[:, 1:-1].copy()
# Get the target
y = train.Cover_Type.copy()

# Create test X, drop ids.
test_X = test.iloc[:, 1:].copy()

In [7]:
X.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
0,3189,40,8,30,13,3270,206,234,193,4873,...,0,0,0,0,0,0,0,0,0,0
1,3026,182,5,280,29,3270,233,240,106,5423,...,0,0,0,0,0,0,0,0,0,0
2,3106,13,7,351,37,2914,208,234,137,5269,...,0,0,0,0,0,0,0,0,0,0
3,3022,276,13,192,16,3034,207,238,156,2866,...,0,0,0,0,0,0,0,0,0,0
4,2906,186,13,266,22,2916,231,231,154,2642,...,0,0,0,0,0,0,0,0,0,0

In [8]:
# Some features are constant, let's remove them
drop_cols = [col for col in X.columns if X[col].nunique() == 1]
X = X.drop(columns=drop_cols)
X.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
0,3189,40,8,30,13,3270,206,234,193,4873,...,0,0,0,0,0,0,0,0,0,0
1,3026,182,5,280,29,3270,233,240,106,5423,...,0,0,0,0,0,0,0,0,0,0
2,3106,13,7,351,37,2914,208,234,137,5269,...,0,0,0,0,0,0,0,0,0,0
3,3022,276,13,192,16,3034,207,238,156,2866,...,0,0,0,0,0,0,0,0,0,0
4,2906,186,13,266,22,2916,231,231,154,2642,...,0,0,0,0,0,0,0,0,0,0

In [9]:
from sklearn.model_selection import train_test_split
import gc
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.compose import ColumnTransformer
from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedKFold
from skopt.space import Real, Categorical, Integer
from skopt import BayesSearchCV
import time

In [10]:
# Splitting the data set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=5)

del X
gc.collect()

X_train

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
2793960,2678,99,7,398,143,-41,204,247,103,1175,...,0,0,0,0,0,0,0,0,0,0
3558660,2684,125,9,108,75,242,230,237,168,3680,...,0,0,0,0,0,0,0,0,0,0
2945915,3006,29,2,222,-9,1693,205,248,29,1563,...,0,0,0,0,1,0,0,0,0,0
2360722,2835,301,6,279,3,2822,188,240,144,132,...,0,0,0,0,0,0,0,0,0,1
2605199,3135,241,18,214,144,2054,198,237,112,1973,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
780455,3332,120,7,327,44,2875,200,178,118,1829,...,0,0,0,0,0,0,0,0,0,0
4574,3098,342,13,435,63,4576,184,228,108,2611,...,0,0,0,0,0,0,0,0,0,0
2439631,3219,346,11,188,58,2070,180,204,81,1852,...,0,1,0,0,0,0,0,0,0,0
2728268,2524,323,2,59,30,1629,236,241,128,1372,...,0,0,0,0,0,0,0,0,0,0
2770909,2624,35,7,212,1,626,181,232,164,704,...,0,0,0,0,0,1,0,0,0,0

In [11]:
# Let's make two lists, one with only one-hot-encoded features, the other with the rest
oh_cols = [col for col in X_train.columns if X_train[col].nunique()==2]
n_oh_cols = [col for col in X_train.columns if X_train[col].nunique()>2]

# this should be zero
len(n_oh_cols)+len(oh_cols)-len(X_train.columns)

0

In [12]:
# Normalising the non-enconded features
sc = StandardScaler()
prep = ColumnTransformer([('sc', sc, n_oh_cols)], remainder='passthrough')

# Define model
model = XGBClassifier(tree_method='gpu_hist', use_label_encoder=False, eval_metric='merror', random_state=7)

# Define pipeline
pipe = Pipeline(steps=[('preprocessing', prep),('model', model)])

In [13]:
# The target needs to be properly enconded, i.e. give 0, 1, 2,...
le = LabelEncoder()
y_train = pd.Series(le.fit_transform(y_train))

In [14]:
# now, we fit using the role train data and the best parameters in the scan
model_opt = XGBClassifier(80, eval_metric='error', use_label_encoder=False, tree_method='gpu_hist')

# Defining the pipeline with the same preprocessing as before, but with the tuned model
pipe_opt = Pipeline(steps=[('preprocessing', prep), ('model', model_opt)])

#transform y_val according to the encoding applied to y_train
y_test = pd.Series(le.transform(y_test))
# Fitting the whole dataset
pipe_opt.fit(X_test, y_test)

del X_test
del y_test
gc.collect()

/opt/conda/lib/python3.7/site-packages/xgboost/core.py:502: FutureWarning: Pass `objective` as keyword args.  Passing these as positional arguments will be considered as error in future releases.
  format(", ".join(args_msg)), FutureWarning

60

In [15]:
### We calculate and store the probability of the positive prediction
X_test = pd.read_csv('../input/tabular-playground-series-dec-2021/test.csv', index_col='Id')

# drop the columns dropped in the train set
X_test = X_test.drop(columns=drop_cols)

pred_test = pipe_opt.predict(X_test)
# inverse transform the results to the original enconding and submit
pred_test = pd.Series(le.inverse_transform(pred_test))

output = pd.DataFrame({'Id': X_test.index,
                       'Cover_Type': pred_test})
output

             Id  Cover_Type
0       4000000           2
1       4000001           2
2       4000002           2
3       4000003           2
4       4000004           2
...         ...         ...
999995  4999995           2
999996  4999996           1
999997  4999997           2
999998  4999998           1
999999  4999999           3

[1000000 rows x 2 columns]

In [16]:
output.to_csv('submission.csv', index=False)